server:
  port : 8000

application:

  resource:
    database:
      url: jdbc:postgresql://localhost/rewards
      username: sergi
      password: 1234

  properties:
    jwt:
      issuer: rewards-uoc
      expirationTime: 60
spring:
  jpa:
    open-in-view: true
    # Skip generating the schema for the database
    generate-ddl: false
    hibernate:
      # Validate the database schema before using it
      ddl-auto: validate

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace
